pull_request_rules:
  - name: Close pull requests to master from branches other than develop
    conditions:
      - base=master
      - head!=develop
    action:
      close:
        message: Please merge into develop
