language: python
python:
  - "3.6"
  - "3.8"
services:
  - redis-server
install:
  - pip install -r requirements.txt
  - pip install .[flask,django]
script:
  python3 -m tox
after_success:
  - codecov
