language: python
python:
  - "3.6"
  - "3.7"
services:
  - redis-server
install:
  - pip install -r requirements.txt
  - pip install .[flask,django]
script:
  python3 -m pytest --cov=chord_lib --cov-branch
after_success:
  - codecov
