__all__ = [
    "WORKFLOW_TYPE_FILE",
    "WORKFLOW_TYPE_FILE_ARRAY",
    "WORKFLOW_TYPE_STRING",
    "WORKFLOW_TYPE_STRING_ARRAY",
    "WORKFLOW_TYPE_ENUM",
    "WORKFLOW_TYPE_ENUM_ARRAY",
    "WORKFLOW_TYPES",
    "WORKFLOW_FILE_TYPES",
]


WORKFLOW_TYPE_ARRAY_SUFFIX = "[]"


def array_of_type(workflow_type: str) -> str:
    return f"{workflow_type}{WORKFLOW_TYPE_ARRAY_SUFFIX}"


WORKFLOW_TYPE_FILE = "file"
WORKFLOW_TYPE_FILE_ARRAY = array_of_type(WORKFLOW_TYPE_FILE)
WORKFLOW_TYPE_STRING = "string"
WORKFLOW_TYPE_STRING_ARRAY = array_of_type("string")
WORKFLOW_TYPE_ENUM = "enum"
WORKFLOW_TYPE_ENUM_ARRAY = array_of_type("enum")

WORKFLOW_TYPES = frozenset((
    WORKFLOW_TYPE_FILE,
    WORKFLOW_TYPE_FILE_ARRAY,
    WORKFLOW_TYPE_STRING,
    WORKFLOW_TYPE_STRING_ARRAY,
    WORKFLOW_TYPE_ENUM,
    WORKFLOW_TYPE_ENUM_ARRAY,
))

WORKFLOW_FILE_TYPES = frozenset((WORKFLOW_TYPE_FILE, WORKFLOW_TYPE_FILE_ARRAY))
