version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    target_branch: "develop"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:patch"
