name: Lint
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        name: Set up Python
        with:
          python-version: '3.12'
      - name: Install poetry
        run: python -m pip install poetry
      - name: Install dev dependencies
        run: python -m poetry install --only dev
      - name: Run format check
        run: poetry run ruff format --check
      - name: Run linter
        run: poetry run ruff check
