name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.6, 3.9 ]
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Test
        run: pytest -svv --cov=bento_lib --cov-branch
      - name: Codecov
        run: codecov
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.6, 3.9 ]
    steps:
      - uses: actions/checkout@v1
      - name: Install bento_lib
        run: pip install .[flask,django]
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run linter
        run: flake8 ./bento_lib ./tests
