name: Test
on:
  push:
    branches:
      - master
      - develop
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11' ]
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch everything for the /service-info builder test
      - uses: actions/setup-python@v4
        name: Set up Python
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: Test
        run: mkdir -p tmp && pytest -svv --cov=bento_lib --cov-branch
        env:
          TEST_REDIS_HOST: localhost
          TEST_REDIS_PORT: 6379
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11' ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        name: Set up Python
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install bento_lib
        run: python -m pip install .
